### ISSUE TITLE
krunkit 0.1.3 broken

### ISSUE THREAD

**Issue by Luap99** [slp/homebrew-krunkit#3]
```
krunkit --version   
dyld[2427]: Library not loaded: @rpath/libvirglrenderer.1.dylib
  Referenced from: <084A01EC-4064-34F7-A9A7-7F799F9D5FFA> /opt/homebrew/Cellar/libkrun-efi/1.9.5/lib/libkrun-efi.1.9.5.dylib
  Reason: no LC_RPATH's found
```

after installing via brew krunkit is failing to run, I have not tried to build krunkit from source to see if this is a issue with the brew build only or a general upstream issue in krunkit

**Comment by slp** [comment]
Yeah, I'm keeping this repo just to simplify packaging, but krunkit is expected to be consumed from podman. We fix the rpaths there. I should probably update the README.md or something.

**Comment by Luap99** [comment]
Sure but right now this broke our CI as the the macos workers consume the dependencies not from the official podman package but rather used brew install and that started to fail 2 days ago in our CI

**Comment by slp** [comment]
Ouch, I wasn't aware of that. Let me update the formula to fix this then.

**Comment by slp** [comment]
I think version `0.1.3b` should fix the issue.

**Comment by Luap99** [comment]
> I think version `0.1.3b` should fix the issue.

Do you know how long it takes for brew to pick these changes up?

```
$ brew install krunkit      
Warning: slp/krunkit/krunkit 0.1.3 is already installed and up-to-date.
```

But to confirm I checked out the repo and directly installed it from here and it seems to work, thanks.

---

Long term I agree our ci workers should not install from brew and use "pinned" versions so we can update them ourselves once we confirmed they work.

**Comment by slp** [comment]
> > I think version `0.1.3b` should fix the issue.
> 
> Do you know how long it takes for brew to pick these changes up?

I think by default it only updates repos after 24 hours from the last update.
 
> ```
> $ brew install krunkit      
> Warning: slp/krunkit/krunkit 0.1.3 is already installed and up-to-date.
> ```
> 
> But to confirm I checked out the repo and directly installed it from here and it seems to work, thanks.

Nice, closing this one then.
